"""blog integration

Revision ID: 89937dcb2053
Revises: a54892d2b8f0
Create Date: 2026-08-28 16:01:03.509527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89937dcb2053'
down_revision: Union[str, Sequence[str], None] = 'a54892d2b8f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_authors'))
    )
    op.create_index(op.f('ix_blog_authors_name'), 'blog_authors', ['name'], unique=False)
    op.create_table('blog_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_blog_users_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_users'))
    )
    op.create_index(op.f('ix_blog_users_customer_id'), 'blog_users', ['customer_id'], unique=False)
    op.create_table('blog_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['blog_authors.id'], name=op.f('fk_blog_articles_author_id_blog_authors')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_blog_articles_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_articles'))
    )
    op.create_index(op.f('ix_blog_articles_author_id'), 'blog_articles', ['author_id'], unique=False)
    op.create_index(op.f('ix_blog_articles_product_id'), 'blog_articles', ['product_id'], unique=False)
    op.create_index(op.f('ix_blog_articles_timestamp'), 'blog_articles', ['timestamp'], unique=False)
    op.create_index(op.f('ix_blog_articles_title'), 'blog_articles', ['title'], unique=False)
    op.create_table('blog_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['blog_users.id'], name=op.f('fk_blog_sessions_user_id_blog_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_sessions'))
    )
    op.create_index(op.f('ix_blog_sessions_user_id'), 'blog_sessions', ['user_id'], unique=False)
    op.create_table('blog_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['blog_articles.id'], name=op.f('fk_blog_views_article_id_blog_articles')),
    sa.ForeignKeyConstraint(['session_id'], ['blog_sessions.id'], name=op.f('fk_blog_views_session_id_blog_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_views'))
    )
    op.create_index(op.f('ix_blog_views_timestamp'), 'blog_views', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_views_timestamp'), table_name='blog_views')
    op.drop_table('blog_views')
    op.drop_index(op.f('ix_blog_sessions_user_id'), table_name='blog_sessions')
    op.drop_table('blog_sessions')
    op.drop_index(op.f('ix_blog_articles_title'), table_name='blog_articles')
    op.drop_index(op.f('ix_blog_articles_timestamp'), table_name='blog_articles')
    op.drop_index(op.f('ix_blog_articles_product_id'), table_name='blog_articles')
    op.drop_index(op.f('ix_blog_articles_author_id'), table_name='blog_articles')
    op.drop_table('blog_articles')
    op.drop_index(op.f('ix_blog_users_customer_id'), table_name='blog_users')
    op.drop_table('blog_users')
    op.drop_index(op.f('ix_blog_authors_name'), table_name='blog_authors')
    op.drop_table('blog_authors')
    # ### end Alembic commands ###
